### ISSUE TITLE
Support multiple links

### ISSUE THREAD

**Issue by jacebrowning** [jacebrowning/gitman#16]
Change the `link` property to `links` (and provide migration) to support creating multiple symlinks into different subdirectories of the dependency.

-----

- [ ] Wait for https://github.com/jacebrowning/gitman/issues/146

**Comment by aepsil0n** [comment]
I would love to take a stab at this, as I find it to be a useful feature. One could easily keep `link` around though so that existing `gitman.yml` continue to work.

**Comment by aepsil0n** [comment]
As a suggestion of what the format could look like:

```
links:
  - source: subfolder1
    target: some/path/within/repo/
  - source: subfolder2
    target: other/path/
```

Here, `source` would be relative to the dependency's working directory, whereas `destination` is relative to the current working directory. Any bike-shedding on this?

**Comment by jacebrowning** [comment]
That sounds pretty good to me!

**Comment by jacebrowning** [comment]
Another (more challenging) option would be to let the `link` attribute be a string or list of string dictionaries for backwards compatibility without adding a new attribute. I might look into that if you are able to get a first pass done using `links`.

**Comment by jacebrowning** [comment]
I have been thinking about this feature more lately and am planning to start implementing it.

The `link` setting will become deprecated and translate to `links` as follows:

- `link: ''` => `links: []`
- `link: foo/bar` => `links: [{'source': '.', 'target': 'foo/bar'}]`

where `source` is relative to the root of the dependency and `target` is relative to the root of the working tree.

This will also allow for links to files:

```yaml
links:
  - source: scripts/foobar.py
    target: bin/foobar
```
