### ISSUE TITLE
Tracking a commit identified by a short SHA does not work

### ISSUE THREAD

**Issue by IagoAbal** [jacebrowning/gitman#166]
I tried tracking a SHA with the following outcome:

> $ gitman update
> ...
> The following command produced a non-zero return code:
> 
> $ git fetch --tags --force --prune origin 6d5546b499e
> fatal: Couldn't find remote ref 6d5546b499e
> fatal: The remote end hung up unexpectedly

But the commit is there:

> $ git show 6d5546b499e 
> commit 6d5546b499e57b318d042eb27097de89f8d239d5
> ...

Not a Git expert, but `git fetch` takes a _refspec_ and that does not include SHAs. Although there seems to be some config options on the server side (such as `uploadpack.allowReachableSHA1InWant`) that may make this work?

Thanks,

**Comment by IagoAbal** [comment]
OK, I was used to tracking branches and I had to re-read the docs to see that `gitman update` only works for branches. It would be great if these kind of errors were caught and reported, but it's my bad. Apologies for a false positive.

**Comment by IagoAbal** [comment]
I did some more experiments and I think I identified the issue.

The following does not work:
> gitman install
```
location: dep
sources:
- name: abc
  repo: <abc-repo>
  rev: 6d5546b499e
```

But this works:
> gitman install
```
location: dep
sources:
- name: abc
  repo: <abc-repo>
  rev: 6d5546b499e57b318d042eb27097de89f8d239d5
```

So it seems that one needs to provide the full commit SHA. I assume this is a bug since the docs say that `rev` can be _all or part of a commit SHA_.
