### ISSUE TITLE
Support dependency groups

### ISSUE THREAD

**Issue by daniel-brosche** [jacebrowning/gitman#187]
In a large project a gitman configuration can contain many dependencies (e.g. 15). 
Dependencies can be dependent from each other and can form logical groups.
In large projects it can happen that not all developers are developing on all parts of the software. So a developer works on a subset of dependencies (dependency group) and is not involved in other dependencies.
In this matter, it would be really helpful to be able to define dependency groups inside the gitman config and to be able to pass these group names to the gitman commands instead of explicitly passing a complete subset (list) of the defined dependency names.

For example:

```yaml
location: imports
sources:
- name: foo-app
  repo: git@foo/foo-app.git
  rev: master
- name: foo-applib
  repo: git@foo/foo-applib.git
  rev: master
- name: foo-app2
  repo: git@foo/foo-applib2.git
  rev: master
- name: foo-applib2
  repo: git@foo/foo-applib2.git
  rev: master
```

An developer that is primary working on foo-app which has only a dependency to foo-applib is currently able to update this logical subset explictly by:
```sh
gitman update foo-app foo-applib
```

When an addtional dependency has been added for foo-app then the developer needs to adapt this call.

To make things easier a gitman config can contain this group information in the gitman config.
So dependencies and dependency-groups can be defined in a centralized way.

For example: 

```yaml
location: imports
sources:
- name: foo-app
  repo: git@foo/foo-app.git
  rev: master
- name: foo-applib
  repo: git@foo/foo-applib.git
  rev: master
- name: foo-app2
  repo: git@foo/foo-applib2.git
  rev: master
- name: foo-applib2
  repo: git@foo/foo-applib2.git
  rev: master

groups:
- name: foo-app-group
  - sources:
     - foo-app
     - foo-applib
```

And the devloper can execute group operations like:
```sh
gitman update foo-app-group
```

There is another [project](https://github.com/nicolas-schmitt/multi-git) that is following this approach.
