### ISSUE TITLE
Add `recurse` option in config

### ISSUE THREAD

**Issue by brandonaut** [jacebrowning/gitman#235]
To avoid recursive clones when there are circular dependencies, `gitman install --depth 1` can be used. However, this is risky as it requires the user to add it on every `gitman install` call. It would be nice to have a `recurse` field in `gitman.yml` to provide a little more control.

For example:
```yaml
location: gitman_sources
sources:
  - name: mydep
    type: git
    repo: https://someurl.com/mydep.git
    recurse: false  # Don't process the gitman.yml in the mydep repo
    sparse_paths:
      -
    rev: master
    link:
    scripts:
      -
groups:
  -
```
