### ISSUE TITLE
Feature request: Add ability to specify a default group for gitman commands

### ISSUE THREAD

**Issue by brandonaut** [jacebrowning/gitman#236]
To help keep gitman commands simple, it would be nice to be able to specify a "default" group in `gitman.yml` that would be used if nothing else is specified in the command.

This default group would also be used if the repo is a nested gitman repo and is being processed recursively by gitman.

For example, perhaps a new field `default_group` could be added:

```yaml
location: .
sources:
  - name: a
    type: git
    repo: https://giturl.com/a.git
    sparse_paths:
      -
    rev: master
    link:
    scripts:
      -
  - name: b
    type: git
    repo: https://giturl.com/b.git
    sparse_paths:
      -
    rev: master
    link:
    scripts:
      -
  # Some dev dependency that most consumers won't need
  - name: c
    type: git
    repo: https://giturl.com/c.git
    sparse_paths:
      -
    rev: master
    link:
    scripts:
      -
default_group: group1
groups:
  - name: group1
    members:
      - a
      - b
```

If `gitman install` is called with no arguments, then it would behave as if it was called with `gitman install group1`.

To support forcing the installation of *all* dependencies, a new flag could be added to most commands (perhaps `--all` to match the `gitman update --all` flag?).

**Comment by Erich-McMillan** [comment]
I think I'm more in favor of the following:

```
groups:
  - name: group1
    default: true
    members:
      - a
      - b
 - name: group2
   members:
    - c
```

Should install accept both 'group1' and 'default' as inputs?
