### ISSUE TITLE
Default groups aren't honored for recursive installs/updates

### ISSUE THREAD

**Issue by brandonaut** [jacebrowning/gitman#245]
If a nested source has it's own `gitman.yaml` and has a `default_group` defined, then when `gitman update` or `gitman install` is called, the `default_group` should be used, instead of updating/installing all sources.

This is kind of similar to #222 , but instead of trying to support passing group/source name arguments to the nested sources, I think the `default_group` should always be used.

For example,

**Parent repo**

```yaml
location: .
sources:
  - name: baked_goods
    type: git
    repo: myurl.com/baked_goods
    sparse_paths:
      -
    rev: main
    link:
    scripts:
      -
```

**baked_goods repo**

```yaml
location: .
sources:
  - name: chocolate_cookies
    type: git
    repo: myurl.com/chocolate_cookies
    sparse_paths:
      -
    rev: main
    link:
    scripts:
      -
 - name: baking_supplies
    type: git
    repo: myurl.com/baking_supplies
    sparse_paths:
      -
    rev: main
    link:
    scripts:
      -
default_group: public
groups:
  - name: public
    members:
      - chocolate_cookies
  - name: dev
    members:
      - chocolate_cookies
      - baking_supplies
```

If I run `gitman install` from the parent repo, then gitman should install `baked_goods/chocolate_cookies` but NOT install `baked_goods/baking_supplies`.
