### ISSUE TITLE
Question: Is it possible to symlink a sub folder of the repository?

### ISSUE THREAD

**Issue by johnneren** [jacebrowning/gitman#247]
Hi :)

I was just wondering if it is possible to symlink a sub folder of a gitman managed repository?

For example my gitman managed sub repository has a folder called:
`Release/Binary/x86` which I would like to link to a `Tool/Config` folder.
But currently it seems that you can only link the root folder to `Tool/Config` or am I missing something?

I also tried working around this by making a 'make_link.py' script located next to my gitman.yaml and then configuring gitman to call this script after checkout. But it seems it only supports calling scripts in the root folder of the managed repository or binaries in the envpath. 

Do you have any suggestion on how I could do this with gitman?

Thanks

**Comment by jacebrowning** [comment]
>  is possible to symlink a sub folder of a gitman managed repository?

Not currently. There is a feature request described in https://github.com/jacebrowning/gitman/issues/16 that would enable this.

> it seems it only supports calling scripts in the root folder of the managed repository or binaries in the envpath

You should be able to work around this with a `gitman.yml` similar to the following:

```
location: .gitman
sources:
  - repo: https://github.com/githubtraining/hellogitworld
    name: hellogitworld
    rev: master
    scripts:
      - mkdir -p ../../Tool/Config
      - ln -sf ../../.gitman/hellogitworld/src/main ../../Tool/Config/main
```

**Comment by johnneren** [comment]
Thanks for the reply Jace :) I missed that you already had a open issue.

I tried a few options based on the script suggestion. One was something like this:
 ```
   scripts:
      - python ../../Tools/make_link.py TranslationFiles/TranslationFiles Platform/TranslationFiles
```
Where I'm using a 'make_link' python script to simplify the yaml file bit.

Another solution I tried was checking out the code and adding support for 'links' in gitman.
I ended up with an attempt where the original 'link' tag still worked as normal and was backwards compatible. If you removed the 'link' tag your could use 'links' instead for more advanced handling. I tried just using a '#' as seperator between dest/src. 
Everything works and the links are being created with the caveat that it won't work with any that has a '#' in it.
Example:
 ```
sources:
  - name: gitman_1
    type: git
    repo: https://github.com/jacebrowning/gitman-demo
    rev: example-branch
    #link: tools/my_link
    links:
      - tools/my_link2#src
      - tools/my_link3#gitman_sources
```
I was also playing around with something like:
```
location: demo
sources:
  - name: gitman_1
    type: git
    repo: https://github.com/jacebrowning/gitman-demo
    rev: example-branch
    #link: tools/my_link
    links:
      - {target: tools/my_link2, source: src}
      - {target: tools/my_link3, source: gitman_sources}
```
But the string based parsing of yaml threw me for a loop and I ran out of time :)
Is there any reason why gitman is not using the yaml module for parsing the configuration file? 
Or is it just because there were no good yaml decoders back in 2015 when you started this project?
