### ISSUE TITLE
Add --no-cone option to sparse checkout

### ISSUE THREAD

**Issue by jferguson3** [jacebrowning/gitman#360]
**3.5.3 (2025-04-24)**
Fixed handling of git cache when using sparse checkouts. (@mastupristi)

Need way to pass `--no-cone` flag to sparse checkout commands

**Comment by mastupristi** [comment]
I will check ASAP

**Comment by CtrlCarlitos** [comment]
First of all, thanks for providing this tool. It's awesome, and it fills my needs incredibly well. So thank you very much!!!

I was struggling with the sparse checkout with my gitman.yml like this:

```
location: /mnt/extra-addons

sources:
  - repo: git@github.com:OCA/web.git
    name: web
    rev: 17.0
    sparse_paths:
      - "web_chatter_position"
      - "web_responsive"

  - repo: git@github.com:OCA/account-financial-reporting.git
    name: account-financial-reporting
    rev: 17.0
    sparse_paths:
      - "account_financial_report"
      - "account_tax_balance"
```

It was pulling all the root files that were giving me a headache. I can confirm with @jferguson3 that the sparse checkout works correctly with Gitman v3.5.2 and Git v2.43.0
