### ISSUE TITLE
Simplify config format

### ISSUE THREAD

**Issue by jacebrowning** [jacebrowning/gitman#80]
Move from:

```yaml
location: gdm_sources
sources:
- dir: api
  link: ''
  repo: https://github.com/example/api
  rev: develop
sources_locked:
- dir: api
  link: ''
  repo: https://github.com/example/api
  rev: b2730855c9efaaa7448b25b82e5a4363785c83ed
```

to 

```yaml
location: gdm_sources
sources:
- name: api
  repository:
    url: https://github.com/example/api
    rev:
      default: develop
      locked: b2730855c9efaaa7448b25b82e5a4363785c83ed
  link: foo/bar
```

where `rev_locked` is optional (along with `link`).
